server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: tonneBois33
    url: jdbc:postgresql://localhost:5432/userplans
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true